### ISSUE TITLE
README, Troubleshooting

### ISSUE THREAD

**Issue by FCACollin** [GeoBosh/Rdpack#19]
FYI, the "_A puzzling message in devtools development mode_" has actually been fixed in [spelling](https://github.com/ropensci/spelling/releases/tag/v2.2).

**Comment by GeoBosh** [comment]
Thanks, but have you checked that it resolves the issue referred to above - namely calling `help()` or `?help` in development mode? I assume that you have but I still get that warning on my computer and my packages cannot be more than a month or so out-of-date (don't know about github versions though). 

Also, looking at https://github.com/ropensci/spelling/issues/42, the issue was closed a year ago but there seem to be comments as recently as September 2020 that the issue persists.

**Comment by FCACollin** [comment]
In a different project, this issue when using Rdpack was specifically fixed by `spelling` upgrading. But I have not been investing beyond that point.
