### ISSUE TITLE
include example?

### ISSUE THREAD

**Issue by andybeet** [GeoBosh/Rdpack#22]
I am trying to use Rdpack for a pkgdown site where i have a lot of references. I can't seem to translate your instructions. I'm sure it's me but i was wondering if you could add a `Rmd` vignette example linking to some references in your REFERENCES.bib?

**Comment by GeoBosh** [comment]
Thanks for your interest in `Rdpack`. If I understand your question correctly, you want to use `Rdpack` for citations in vignettes (in that case see below). Or do you just prefer a html vignette rather than the pdf vignette in the package?

The setup described in README and the vignette is for references and citations in the roxygen2 (or Rd) 
documentation). My package 'mixAR' ("GeoBosh/mixAR") has a lot of references and pkgdown site. The docs are Rd (so you need to look the Rd sources under man/) but the reference and citation macros are used in the same way in roxygen2.

The underlying functions can be used in `Rmd` files and I could write wrappers and examples to make this smooth. But isn't it better to use markdown syntax for citations and may be just copy REFERENCES.bib to directory `vignettes/`?

Let me know if I have misunderstood your question or have missed the point.
